name: Auto Publish Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki-pages/**'
      - '.github/workflows/auto-wiki.yml'
  workflow_dispatch:

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Publish Wiki
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if wiki-pages directory exists
          const wikiDir = 'wiki-pages';
          if (!fs.existsSync(wikiDir)) {
            console.log('❌ wiki-pages directory not found');
            return;
          }
          
          // Read all markdown files
          const files = fs.readdirSync(wikiDir)
            .filter(file => file.endsWith('.md'))
            .sort();
          
          if (files.length === 0) {
            console.log('❌ No markdown files found in wiki-pages');
            return;
          }
          
          console.log(`📚 Found ${files.length} wiki pages to publish`);
          
          // Create a temporary directory for the wiki
          await exec.exec('mkdir', ['wiki-temp']);
          
          // Copy files to temp directory
          for (const file of files) {
            const content = fs.readFileSync(path.join(wikiDir, file), 'utf8');
            fs.writeFileSync(path.join('wiki-temp', file), content);
            console.log(`✅ Prepared: ${file}`);
          }
          
          // Initialize git repo for wiki
          process.chdir('wiki-temp');
          await exec.exec('git', ['init']);
          await exec.exec('git', ['config', 'user.name', 'github-actions[bot]']);
          await exec.exec('git', ['config', 'user.email', 'github-actions[bot]@users.noreply.github.com']);
          await exec.exec('git', ['add', '.']);
          
          // Check if there are changes
          let status = '';
          try {
            await exec.exec('git', ['status', '--porcelain'], { 
              silent: true,
              listeners: {
                stdout: (data) => { status += data.toString(); },
                stderr: (data) => { console.error(data.toString()); }
              }
            });
          } catch (error) {
            console.log('Error checking git status:', error);
          }
          
          if (!status.trim()) {
            console.log('ℹ️ No changes to publish');
            return;
          }
          
          await exec.exec('git', ['commit', '-m', '📚 Update wiki pages [auto]']);
          
          // Try to push to wiki
          try {
            // Use the GITHUB_TOKEN from environment
            const token = '${{ secrets.GITHUB_TOKEN }}';
            // Try main branch first, then master as fallback
            try {
              await exec.exec('git', ['push', '-f', `https://${token}@github.com/${{ github.repository }}.wiki.git`, 'main:main']);
            } catch (mainError) {
              console.log('⚠️ main branch push failed, trying master...');
              await exec.exec('git', ['push', '-f', `https://${token}@github.com/${{ github.repository }}.wiki.git`, 'master:main']);
            }
            console.log('✅ Wiki published successfully!');
          } catch (error) {
            console.log('⚠️ Push failed, wiki might not exist yet');
            console.log('📝 You may need to create the first page manually at:');
            console.log(`   https://github.com/${{ github.repository }}/wiki`);
          }
          
          process.chdir('..');
          
          // Create summary
          console.log('## 📚 Wiki Publication Summary');
          console.log('');
          console.log('### 📄 Pages Published:');
          for (const file of files) {
            const name = file.replace('.md', '');
            console.log(`- [${name}](https://github.com/${{ github.repository }}/wiki/${name})`);
          }
          console.log('');
          console.log('### 🔗 Links:');
          console.log(`- [📖 View Wiki](https://github.com/${{ github.repository }}/wiki)`);
          console.log(`- [⚙️ Manage Wiki](https://github.com/${{ github.repository }}/wiki/_pages)`);