name: Auto Build Dist

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.ts'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build dist
        run: bun run build.ts

      - name: Commit dist if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist/
          git diff --staged --quiet || git commit -m "chore: auto-build dist [skip ci]"
          git push
