name: Deploy Wiki

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki-pages/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy Wiki 🚀
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      with:
        path: wiki-pages
        token: ${{ secrets.GITHUB_TOKEN }}